### ISSUE TITLE
Myslqi compatibility ! (update by me)

### ISSUE THREAD

**Issue by Tom60chat** [clockfree/Global-Account-System-GAS---Unity#1]
Bonjour !
I work for a litle update to you assets, here a zip file with all the file.
*php mail fonction don't work with outlook.

Here the file: [](https://mega.nz/#F!WstEyKhS!gg6weLlgw8cEfKuB2Xqscw)

Have a nice day !
(sorry tu publish here, pull requets are private)

**Comment by ammariqais** [comment]
sorry for the late response, I invited you to be collaborator, nice work my friend :)

**Comment by Tom60chat** [comment]
Thank you, so I created a "MySQLi-PHP7" branch with all my update work.

**Comment by ammariqais** [comment]
merged with master :)
